#!/bin/bash

re='^[0-9]+$'
initialCount=1
n=1
dir=.
shuffle=false

while getopts 'n:i:s' flag; do
	case "${flag}" in
	i) dir=$OPTARG ;;
    n) 
		if [[ $OPTARG =~ $re ]] ; then
			initialCount=$OPTARG;
			n=$initialCount;
		fi ;;
    s) shuffle=true ;;
    *) error "Unexpected option ${flag}r" ;;
  esac
done

IFS=$'\n'

fileArray=( )

if $shuffle ; then
  fileArray=( $(find "$dir" -type d -print0 | xargs -0 -I{} find -E '{}' -maxdepth 1 -iregex ".*/[^.]*\.(jpg|jpeg|png|gif|bmp|tiff|tif)") )

else
  pattern="[^.]*\.(jpg|jpeg|png|gif|bmp|tiff|tif)"

  for directory in $(find "$dir" -type d); do
  	for file in "$directory"/*; do
  	  if [[ ${file##*/} =~ $pattern ]] ; then
  	    fileArray+=( "$file" )
  	    break 1;
      fi
  	done;
  done
fi;

unset IFS;

printf "${#fileArray[@]} images found\nOpening "$n" images\n\n";

while true; do
	for i in $(eval echo {1..$n}); do
		selected="${fileArray[RANDOM%${#fileArray[@]}]}"
		path=${selected##"$dir"}
		echo ${path#"/"}
		open "$selected"
	done;
	n=$initialCount;
	printf "\n"
	read -n 1 -s -r -p "Press any key to continue. Press a number to open that many photos" key;
	printf "\n\n"
	if [[ $key =~ $re ]] ; then
		n=$key;
	fi
done;
