#!/bin/bash
shuffle=false
dir=.
playlist=./playlist.m3u
tempfile=./tempfile

while getopts 'sf:n:' flag; do
  case "${flag}" in
    s) shuffle=true ;;
    *) error "Unexpected option ${flag}" ;;
  esac
done

find $dir -iregex "[^\.]*.avi" -or -iname "[^\.]*.mkv" -or -iname "[^\.]*.mp4" -or -iname "[^\.]*.wmv" -or -iname "[^\.]*.mov" -or -iname "[^\.]*.webm" -or -iname "[^\.]*.mpg" -or -iname "[^\.]*.flv"> $tempfile 

if  [ "$shuffle" = true ] ;
then
	gshuf $tempfile > $playlist
        rm $tempfile
else
	mv $tempfile $playlist
fi

 
